---
- hosts: gpu

  tasks:
    - name: get kubeadm token from leader
      shell: kubeadm token create --print-join-command
      delegate_to: "{{ item }}"
      loop: "{{ groups['leader'] }}"
      register: k8_join_command
      run_once: true

    - name: joining cluster
      become: true
      shell: " {{ item.stdout }}"
      loop: "{{ k8_join_command.results }}"

- hosts: leader

  tasks:

    - name: testing access to cluster
      shell: kubectl get nodes
      register: get_nodes
      become_user: ubuntu

    - name: printing get_nodes
      debug:
        msg: "{{ get_nodes }}"
