---
- hosts: gpu

  tasks:
    - name: get kubeadm token from leader
      shell: kubeadm token create --print-join-command
      delegate_to: "{{ item }}"
      loop: "{{ groups['leader'] }}"
      register: k8_join_command
      run_once: true

    - name: joining cluster
      become: true
      shell: " {{ item.stdout }}"
      loop: "{{ k8_join_command.results }}"

    - name: install nvidia-container-toolkit
      become: true
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -
        curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sudo tee /etc/apt/sources.list.d/libnvidia-container.list
        apt-get update && apt-get install -y nvidia-container-toolkit

    - name: configure docker
      become: true
      shell: | 
        echo '{
            "default-runtime": "nvidia",
            "runtimes": {
                "nvidia": {
                    "path": "/usr/bin/nvidia-container-runtime",
                    "runtimeArgs": []
                }
            }
        }' > /etc/docker/daemon.json

    - name: restart docker
      become: true
      shell: systemctl restart docker

    - name: configure containerd
      become: true
      shell: |
        curl -O https://raw.githubusercontent.com/nosolls/terraform-js2-k8cluster/main/config.toml && cp config.toml /etc/containerd/config.toml

    - name: restart containerd
      become: true
      shell: systemctl restart containerd

- hosts: leader

  tasks:

    - name: testing access to cluster
      shell: kubectl get nodes
      register: get_nodes
      become_user: ubuntu

    - name: printing get_nodes
      debug:
        msg: "{{ get_nodes }}"

    - name: Enable GPU Support in Kubernetes
      shell: kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.4/nvidia-device-plugin.yml
