---
- hosts: all
  become: true

  tasks:
    - name: creating containerd.config
      ansible.builtin.file:
        path: /etc/modules-load.d/containerd.config
        state: touch

    - name: setting up containerd
      ansible.builtin.blockinfile:
        path: /etc/modules-load.d/containerd.config
        insertafter: EOF
        block: |
          overlay
          br_netfilter
    - name: Loading kernal modules
      ansible.builtin.shell:
        cmd: /usr/sbin/modprobe overlay

    - name: Loading kernal modules
      ansible.builtin.shell:
        cmd: /usr/sbin/modprobe br_netfilter

    - name: Setting up Networking for K8s
      ansible.posix.sysctl:
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        name: "{{ item }}"
        value: '1'
        reload: true
      loop:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables

    - name: Installing containerd and k8 dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - containerd
        - apt-transport-https
        - curl


    - name: creating /etc/containerd
      ansible.builtin.file:
        path: /etc/containerd
        state: directory

    - name: creating containerd/config.toml
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: touch

    - name: Setting default config for containerd
      ansible.builtin.shell: "containerd config default > /etc/containerd/config.toml"

    - name: restarting containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

    - name: turning off swap
      ansible.builtin.shell: "swapoff -a"

    - name: Adding K8 apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg.asc
        state: present

    - name: Adding K8 repo (kubernetes-xenial)
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Installing K8 packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - kubelet
        - kubeadm
        - kubectl
    - name: creating /etc/docker/daemon.json
      ansible.builtin.file:
        path: /etc/docker/daemon.json
        state: touch

    - name: Changing docker driver to systemd
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        src: daemon.json
        backup: true

    - name: reloading systemctl daemon and restarting docker
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: restarting kubeadm
      ansible.builtin.shell:
        cmd: kubeadm reset -f
