---
- hosts: all
  become: true

  tasks:
    - name: Updating apt-cache
      apt:
        update_cache: true

    - name: creating containerd.config
      file:
        path: /etc/modules-load.d/containerd.config
        state: touch

    - name: setting up containerd
      blockinfile:
        path: /etc/modules-load.d/containerd.config
        insertafter: EOF
        block: |
          overlay
          br_netfilter
    - name: Loading kernal modules
      shell:
        cmd: /usr/sbin/modprobe overlay

    - name: Loading kernal modules
      shell:
        cmd: /usr/sbin/modprobe br_netfilter

    - name: Setting up Networking for K8s
      sysctl:
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        name: "{{ item }}"
        value: '1'
        reload: true
      loop:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables

    - name: Installing containerd and k8 dependencies
      apt:
        name: [containerd, apt-transport-https, curl]
        state: present

    - name: creating /etc/containerd
      file:
        path: /etc/containerd
        state: directory

    - name: creating containerd/config.toml
      file:
        path: /etc/containerd/config.toml
        state: touch

    - name: Setting default config for containerd
      shell: "containerd config default > /etc/containerd/config.toml"

    - name: restarting containerd
      service:
        name: containerd
        state: restarted

    - name: turning off swap
      shell: "swapoff -a"

    - name: Adding K8 apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg.asc
        state: present

    - name: Adding K8 repo (kubernetes-xenial)
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Installing K8 packages
      apt:
        name: [kubelet, kubeadm, kubectl]
        state: present
        update_cache: true

    - name: creating /etc/docker/daemon.json
      file:
        path: /etc/docker/daemon.json
        state: touch

    - name: Changing docker driver to systemd
      copy:
        dest: /etc/docker/daemon.json
        src: daemon.json
        backup: true

    - name: reloading systemctl daemon and restarting docker
      systemd:
        state: restarted
        daemon_reload: true
        name: docker

    - name: restarting kubeadm
      shell:
        cmd: kubeadm reset -f
